[font]

normal = {family = "Lilex Nerd Font", style = "Regular"}
bold = {family = "Lilex Nerd Font", style = "Bold"}
italic = {family = "Lilex Nerd Font", style = "Italic"}
size = 11.0

[env]

WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]

padding = { x = 10, y = 10 }
